# site settings
title: The Best and Safest Way to Explore Egypt
subtitle: by Everywhere Tours Egypt
email: mohamedtamer92@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/travelagency" # the subpath of your site, e.g. /blog
url: "https://fattouh92.github.io" # the base hostname & protocol for your site
author: Everywhere Tours Egypt
street_address: Südtirolerstraße 27
city: Linz
state: Upper Austria
zip_code: 4020
country: Austria
phone: +43 664 4787

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram: 
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
# markdown: kramdown
remote_theme: "andrewbanchich/forty-jekyll-theme"
plugins:
  - jekyll-feed

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
